routes/web.php
<?php

declare(strict_types=1);

use App\Http\Controllers\Auth\AuthenticateUserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\RegistrationController;
use App\Http\Controllers\Auth\StoreRegistrationController;
use App\Http\Controllers\Callouts\CreateCalloutController;
use App\Http\Controllers\Callouts\ListCalloutsController;
use App\Http\Controllers\Callouts\ShowCalloutController;
use App\Http\Controllers\Callouts\StoreCalloutController;
use App\Http\Controllers\Contact\ContactUsPageController;
use App\Http\Controllers\Contact\ProcessContactUsController;
use App\Http\Controllers\Defibs\CreateDefibController;
use App\Http\Controllers\Defibs\EditDefibController;
use App\Http\Controllers\Defibs\Inspections\CreateDefibInspectionController;
use App\Http\Controllers\Defibs\Inspections\StoreDefibInspectionController;
use App\Http\Controllers\Defibs\ListDefibsController;
use App\Http\Controllers\Defibs\Notes\CreateDefibNoteController;
use App\Http\Controllers\Defibs\Notes\StoreDefibNoteController;
use App\Http\Controllers\Defibs\StoreDefibController;
use App\Http\Controllers\Defibs\UpdateDefibController;
use App\Http\Controllers\Defibs\ViewDefibController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\Members\CreateMemberController;
use App\Http\Controllers\Members\EditMemberController;
use App\Http\Controllers\Members\ListMembersController;
use App\Http\Controllers\Members\Notes\CreateMemberNoteController;
use App\Http\Controllers\Members\Notes\StoreMemberNoteController;
use App\Http\Controllers\Members\StoreMemberController;
use App\Http\Controllers\Members\UpdateMemberController;
use App\Http\Controllers\Members\ViewMemberController;
use App\Http\Controllers\Users\InviteUserController;
use App\Http\Controllers\Users\ListUsersController;
use App\Http\Controllers\Users\ShowRequestedReportsController;
use App\Http\Controllers\Users\ShowUserController;
use App\Http\Controllers\Users\ShowUserPermissionsController;
use App\Http\Controllers\Users\StoreRequestedReportsController;
use App\Http\Controllers\Users\StoreUserInvitationController;
use App\Http\Controllers\Users\UpdateUserPermissionsController;
use Illuminate\Support\Facades\Route;

Route::get('/', IndexController::class)->name('index');

Route::get('/contact', ContactUsPageController::class)->name('contact.create');
Route::post('/contact', ProcessContactUsController::class)->name('contact.store');

Route::middleware('guest')->group(function () {
    Route::get('/login', LoginController::class)->name('login.create');
    Route::post('/login', AuthenticateUserController::class)->name('login.store');
    Route::get('/register/{invite:token}', RegistrationController::class)->name('register.create');
    Route::post('/register', StoreRegistrationController::class)->name('register.store');
});

Route::middleware('auth')->group(function () {
    Route::post('logout', LogoutController::class)->name('auth.logout');

    Route::prefix('defibs')->name('defibs.')->group(function () {
        Route::get('/', ListDefibsController::class)->name('list')->can('defib.list');
        Route::post('/', StoreDefibController::class)->name('store')->can('defib.create');
        Route::get('/new', CreateDefibController::class)->name('create')->can('defib.create');
        Route::get('/{defib}', ViewDefibController::class)->name('view')->can('defib.view');
        Route::get('/{defib}/update', EditDefibController::class)->name('edit')->can('defib.update');
        Route::put('/{defib}', UpdateDefibController::class)->name('update')->can('defib.update');

        Route::prefix('/{defib}/inspections')->name('inspections.')->group(function () {
            Route::get('/new', CreateDefibInspectionController::class)->name('create')->can('defib.inspect');
            Route::post('/', StoreDefibInspectionController::class)->name('store')->can('defib.inspect');
        });

        Route::prefix('/{defib}/notes')->name('notes.')->group(function () {
            Route::get('/new', CreateDefibNoteController::class)->name('create')->can('defib.note');
            Route::post('/', StoreDefibNoteController::class)->name('store')->can('defib.note');
        });
    });

    Route::prefix('members')->name('members.')->group(function () {
        Route::get('/', ListMembersController::class)->name('list')->can('member.list');
        Route::post('/', StoreMemberController::class)->name('store')->can('member.create');
        Route::get('/new', CreateMemberController::class)->name('create')->can('member.create');
        Route::get('/{member}', ViewMemberController::class)->name('view')->can('member.view');
        Route::get('/{member}/update', EditMemberController::class)->name('edit')->can('member.update');
        Route::put('/{member}', UpdateMemberController::class)->name('update')->can('member.update');

        Route::prefix('/{member}/notes')->name('notes.')->group(function () {
            Route::get('/new', CreateMemberNoteController::class)->name('create')->can('member.note');
            Route::post('/', StoreMemberNoteController::class)->name('store')->can('member.note');
        });
    });

    Route::prefix('callouts')->name('callouts.')->group(function () {
        Route::get('/', ListCalloutsController::class)->name('list')->can('callout.list');
        Route::post('/', StoreCalloutController::class)->name('store')->can('callout.create');
        Route::get('/new', CreateCalloutController::class)->name('create')->can('callout.create');
        Route::get('/{callout}', ShowCalloutController::class)->name('show')->can('callout.view');
    });

    Route::prefix('users')->name('users.')->group(function () {
        Route::get('/', ListUsersController::class)->name('list')->can('user.list');
        Route::get('/invite', InviteUserController::class)->name('invite.create')->can('user.invite');
        Route::post('/invite', StoreUserInvitationController::class)->name('invite.store')->can('user.invite');
        Route::get('/{user}', ShowUserController::class)->name('show')->can('user.view');
        Route::get('/{user}/reports', ShowRequestedReportsController::class)->name('reports.show')->can('user.update');
        Route::put('/{user}/reports', StoreRequestedReportsController::class)->name('reports.store')->can('user.update');
        Route::get('/{user}/permissions', ShowUserPermissionsController::class)->name('permissions.show')->can('user.permissions');
        Route::put('/{user}/permissions', UpdateUserPermissionsController::class)->name('permissions.update')->can('user.permissions');
    });
});

app/Models/User.php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasRoles;
    use HasFactory;
    use Notifiable;
    use SoftDeletes;

    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    protected $hidden = [
        'password',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
        'last_login_at' => 'datetime',
    ];

    protected $rememberTokenName = '';

    public function reports(): HasOne
    {
        return $this->hasOne(UserReport::class);
    }
}

app/Http/Controllers/Users/InviteUserController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Users;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class InviteUserController extends Controller
{
    public function __invoke(Request $request): View
    {
        return view('users.invite');
    }
}

app/Http/Controllers/Users/ListUsersController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Users;

use App\Http\Controllers\Controller;
use App\Models\Invite;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class ListUsersController extends Controller
{
    public function __invoke(Request $request): View
    {
        $users = User::paginate(10);
        $invites = Invite::all();

        return view('users.list', ['users' => $users, 'invites' => $invites]);
    }
}

app/Http/Controllers/Users/ShowRequestedReportsController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Users;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class ShowRequestedReportsController extends Controller
{
    public function __invoke(Request $request, User $user): View
    {
        $user->with('reports');

        if (! $user->reports) {
            $user->reports()->create();
            $user->refresh();
        }

        return view('users.reports', ['user' => $user]);
    }
}

app/Http/Controllers/Users/ShowUserController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Users;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class ShowUserController extends Controller
{
    public function __invoke(Request $request, User $user): View
    {
        return view('users.show', ['user' => $user]);
    }
}

app/Http/Controllers/Users/ShowUserPermissionsController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Users;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Permission;

class ShowUserPermissionsController extends Controller
{
    public function __invoke(Request $request, User $user): View
    {
        $user->with('permissions');

        $permissions = Permission::orderBy('name')->get();

        return view('users.permissions', ['user' => $user, 'permissions' => $permissions]);
    }
}

app/Http/Controllers/Users/StoreRequestedReportsController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Users;

use App\Http\Controllers\Controller;
use App\Http\Requests\Users\StoreRequestedReportsRequest;
use App\Models\User;
use Illuminate\Http\RedirectResponse;

class StoreRequestedReportsController extends Controller
{
    public function __invoke(StoreRequestedReportsRequest $request, User $user): RedirectResponse
    {
        if (! $user->reports) {
            abort(500);
        }

        $user->reports->update([
            'cfr_cert_expiry' => $request->get('cfr_cert_expiry') === 'Yes',
            'defib_battery_expiry' => $request->get('defib_battery_expiry') === 'Yes',
            'defib_inspection' => $request->get('defib_inspection') === 'Yes',
            'defib_pad_expiry' => $request->get('defib_pad_expiry') === 'Yes',
            'garda_vetting_expiry' => $request->get('garda_vetting_expiry') === 'Yes',
            'defib_inspected' => $request->get('defib_inspected') === 'Yes',
        ]);

        return redirect()->route('users.show', ['user' => $user])->with('success', 'Requested Reports Updated Successfully');
    }
}

app/Http/Controllers/Users/StoreUserInvitationController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Users;

use App\Http\Controllers\Controller;
use App\Http\Requests\Users\StoreUserInvitationRequest;
use App\Mail\UserInvitationMail;
use App\Models\Invite;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Mail;

class StoreUserInvitationController extends Controller
{
    public function __invoke(StoreUserInvitationRequest $request): RedirectResponse
    {
        $invite = new Invite($request->validated());
        $invite->user_id = auth()->user()->id;
        $invite->token = substr(md5(rand(0, 9).$invite->email.time()), 0, 32);
        $invite->expires_at = now()->addHours(48);
        $invite->save();

        Mail::to($invite->email)->queue(new UserInvitationMail($invite));

        return redirect()->route('users.list')->with('success', 'User Successfully Invited');
    }
}

app/Http/Controllers/Users/UpdateUserPermissionsController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Users;

use App\Http\Controllers\Controller;
use App\Http\Requests\Users\UpdateUserPermissionsRequest;
use App\Models\User;
use Illuminate\Http\RedirectResponse;

class UpdateUserPermissionsController extends Controller
{
    public function __invoke(UpdateUserPermissionsRequest $request, User $user): RedirectResponse
    {
        $user->permissions()->sync($request->get('permissions'));

        return redirect()->route('users.show', ['user' => $user])->with('success', 'User Permissions Successfully Updated');
    }
}

app/View/Components/AppLayout.php
<?php

declare(strict_types=1);

namespace App\View\Components;

use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class AppLayout extends Component
{
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/users/invite.blade.php
<x-app-layout>
    <div class="overflow-hidden bg-white shadow sm:rounded-lg">
        <div class="sm:flex sm:items-center py-5 px-4 sm:px-6 lg:px-8">
            <div class="sm:flex-auto">
                <h1 class="text-xl font-semibold text-gray-900">Invite User</h1>
            </div>
            <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
            </div>
        </div>
        <div class="border-t border-gray-200 px-4 py-5 sm:p-0">
            <form action="{{ route('users.invite.store') }}" method="post">
                @csrf
                <dl class="sm:divide-y sm:divide-gray-200">
                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500"><label for="name">Name</label></dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <input type="text" name="name" id="name" class="block @error('name') border-red-500 @enderror w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm">
                            @error('name')
                            <div class="text-sm text-red-600">{{ $message }}</div>
                            @enderror
                        </dd>
                    </div>

                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500"><label for="email">Email Address</label></dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <input type="email" name="email" id="email" class="block @error('email') border-red-500 @enderror w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm">
                            @error('email')
                            <div class="text-sm text-red-600">{{ $message }}</div>
                            @enderror
                        </dd>
                    </div>

                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            <button type="submit" class="inline-flex justify-center rounded-md border border-transparent bg-red-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2">Invite</button>
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <button type="button" class="rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2">Cancel</button>
                        </dd>
                    </div>
                </dl>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/users/list.blade.php
<x-app-layout>
    <div x-data="{ modelOpen: false }" class="overflow-hidden bg-white shadow sm:rounded-lg px-4 sm:px-6 lg:px-8">
        <div class="sm:flex sm:items-center py-5">
            <div class="sm:flex-auto">
                <h1 class="text-xl font-semibold text-gray-900">Users</h1>
            </div>
            <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
                @can('user.invite')
                    <a href="{{ route('users.invite.create') }}">
                        <button type="button" class="inline-flex items-center justify-center rounded-md border border-transparent bg-red-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 sm:w-auto">Invite User</button>
                    </a>
                    <button @click="modelOpen =!modelOpen" class="inline-flex items-center justify-center rounded-md border border-transparent bg-red-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 sm:w-auto">
                        Show Invites
                    </button>
                @endcan
            </div>
        </div>
        <div class="flex flex-col">
            <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="inline-block min-w-full py-2 align-middle">
                    <div class="overflow-hidden shadow-sm ring-1 ring-black ring-opacity-5">
                        <table class="min-w-full divide-y divide-gray-300">
                            <thead class="bg-gray-50">
                            <tr>
                                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6 lg:pl-8">Name</th>
                                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Email Address</th>
                                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Last Login At</th>
                                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Last Login From</th>
                                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6 lg:pr-8">
                                    <span class="sr-only">View</span>
                                </th>
                            </tr>
                            </thead>
                            <tbody class="divide-y divide-gray-200 bg-white">
                                @foreach($users as $user)
                                    <tr>
                                        <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">{{ $user->name }}</td>
                                        <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ $user->email }}</td>
                                        <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ $user->last_login_at?->format('Y-m-d H:i:s') }}</td>
                                        <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ $user->last_login_from }}</td>
                                        <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                                            <a href="{{ route('users.show', ['user' => $user]) }}" class="text-red-600 hover:text-red-900">View<span class="sr-only">, {{ $user->name }}</span></a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            {{ $users->links('pagination::tailwind') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div x-show="modelOpen" class="fixed inset-0 z-50" aria-labelledby="modal-title" role="dialog" aria-modal="true">
            <div class="flex items-end justify-center min-h-screen px-4 text-center md:items-center sm:block sm:p-0">
                <div x-cloak @click="modelOpen = false" x-show="modelOpen"
                     x-transition:enter="transition ease-out duration-300 transform"
                     x-transition:enter-start="opacity-0"
                     x-transition:enter-end="opacity-100"
                     x-transition:leave="transition ease-in duration-200 transform"
                     x-transition:leave-start="opacity-100"
                     x-transition:leave-end="opacity-0"
                     class="fixed inset-0 transition-opacity bg-gray-500 bg-opacity-40" aria-hidden="true"
                ></div>

                <div x-cloak x-show="modelOpen"
                     x-transition:enter="transition ease-out duration-300 transform"
                     x-transition:enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                     x-transition:enter-end="opacity-100 translate-y-0 sm:scale-100"
                     x-transition:leave="transition ease-in duration-200 transform"
                     x-transition:leave-start="opacity-100 translate-y-0 sm:scale-100"
                     x-transition:leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                     class="inline-block w-full max-w-4xl p-8 my-20 overflow-hidden text-left transition-all transform bg-white rounded-lg shadow-xl"
                >
                    <div class="sm:flex-auto">
                        <h1 class="text-xl font-semibold text-gray-900">Invites</h1>
                    </div>

                    <table class="min-w-full divide-y divide-gray-300">
                        <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6 lg:pl-8">Name</th>
                            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Email Address</th>
                            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Invited At</th>
                            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Expires At</th>
                            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Registered At</th>
                        </tr>
                        </thead>
                        <tbody class="divide-y divide-gray-200 bg-white">
                        @foreach($invites as $invite)
                            <tr>
                                <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">{{ $invite->name }}</td>
                                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ $invite->email }}</td>
                                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ $invite->created_at }}</td>
                                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ $invite->expires_at }}</td>
                                <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ $invite->registered_at }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/users/permissions.blade.php
<x-app-layout>
{{--@dd($user->permissions, $permissions)--}}
    <div class="overflow-hidden bg-white shadow sm:rounded-lg">
        <div class="sm:flex sm:items-center py-5 px-4 sm:px-6 lg:px-8">
            <div class="sm:flex-auto">
                <h1 class="text-xl font-semibold text-gray-900">Manage Permissions for {{ $user->name }}</h1>
            </div>
        </div>

        <div class="border-t border-gray-200 px-4 py-5 sm:p-0">
            <dl class="sm:divide-y sm:divide-gray-200">
                <form action="{{ route('users.permissions.update', ['user' => $user]) }}" method="post">
                    @csrf
                    @method('PUT')

                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <fieldset>
                            <div class="mt-4 divide-y divide-gray-200 border-b border-gray-200">
                                @if($errors->hasAny())

                                    @dd($errors)
                                @endif
                                @foreach($permissions as $permission)
                                    <div class="relative flex items-start py-4">
                                        <div class="min-w-0 flex-1 text-sm">
                                            <label for="permissions" class="select-none font-medium text-gray-700">{{ ucwords(str_replace('.', ' ', $permission->name)) }}</label>
                                        </div>
                                        <div class="ml-3 flex h-5 items-center">
                                            <input id="permissions" name="permissions[]" type="checkbox" class="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500" value="{{ $permission->id }}" @checked($user->can($permission->name))>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </fieldset>
                    </div>

                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            <button type="submit" class="inline-flex justify-center rounded-md border border-transparent bg-red-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2">Update</button>
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <a href="{{ route('users.show', ['user' => $user]) }}"><button type="button" class="rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2">Cancel</button></a>
                        </dd>
                    </div>
                </form>
            </dl>
        </div>
    </div>
</x-app-layout>

resources/views/users/show.blade.php
<x-app-layout>
    <div class="overflow-hidden bg-white shadow sm:rounded-lg">
        <div class="sm:flex sm:items-center py-5 px-4 sm:px-6 lg:px-8">
            <div class="sm:flex-auto">
                <h1 class="text-xl font-semibold text-gray-900">User Details</h1>
            </div>
            <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
                @can('user.permissions')
                    <a href="{{ route('users.permissions.show', ['user' => $user]) }}">
                        <button type="button" class="inline-flex items-center justify-center rounded-md border border-transparent bg-red-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 sm:w-auto">Manage Permissions</button>
                    </a>
                @endcan
                @can('user.update')
                    <a href="{{ route('users.reports.show', ['user' => $user]) }}">
                        <button type="button" class="inline-flex items-center justify-center rounded-md border border-transparent bg-red-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 sm:w-auto">Requested Reports</button>
                    </a>
                @endcan
            </div>
        </div>
        <div class="border-t border-gray-200 px-4 py-5 sm:p-0">
            <dl class="sm:divide-y sm:divide-gray-200">
                <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                    <dt class="text-sm font-medium text-gray-500">Name</dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">{{ $user->name }}</dd>
                </div>

                <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                    <dt class="text-sm font-medium text-gray-500">Email Address</dt>
                    <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">{{ $user->email }}</dd>
                </div>
            </dl>
        </div>
    </div>
</x-app-layout>