routes/web.php
<?php

declare(strict_types=1);

use App\Http\Controllers\Auth\AuthenticateUserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\RegistrationController;
use App\Http\Controllers\Auth\StoreRegistrationController;
use App\Http\Controllers\Callouts\CreateCalloutController;
use App\Http\Controllers\Callouts\ListCalloutsController;
use App\Http\Controllers\Callouts\ShowCalloutController;
use App\Http\Controllers\Callouts\StoreCalloutController;
use App\Http\Controllers\Contact\ContactUsPageController;
use App\Http\Controllers\Contact\ProcessContactUsController;
use App\Http\Controllers\Defibs\CreateDefibController;
use App\Http\Controllers\Defibs\EditDefibController;
use App\Http\Controllers\Defibs\Inspections\CreateDefibInspectionController;
use App\Http\Controllers\Defibs\Inspections\StoreDefibInspectionController;
use App\Http\Controllers\Defibs\ListDefibsController;
use App\Http\Controllers\Defibs\Notes\CreateDefibNoteController;
use App\Http\Controllers\Defibs\Notes\StoreDefibNoteController;
use App\Http\Controllers\Defibs\StoreDefibController;
use App\Http\Controllers\Defibs\UpdateDefibController;
use App\Http\Controllers\Defibs\ViewDefibController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\Members\CreateMemberController;
use App\Http\Controllers\Members\EditMemberController;
use App\Http\Controllers\Members\ListMembersController;
use App\Http\Controllers\Members\Notes\CreateMemberNoteController;
use App\Http\Controllers\Members\Notes\StoreMemberNoteController;
use App\Http\Controllers\Members\StoreMemberController;
use App\Http\Controllers\Members\UpdateMemberController;
use App\Http\Controllers\Members\ViewMemberController;
use App\Http\Controllers\Users\InviteUserController;
use App\Http\Controllers\Users\ListUsersController;
use App\Http\Controllers\Users\ShowRequestedReportsController;
use App\Http\Controllers\Users\ShowUserController;
use App\Http\Controllers\Users\ShowUserPermissionsController;
use App\Http\Controllers\Users\StoreRequestedReportsController;
use App\Http\Controllers\Users\StoreUserInvitationController;
use App\Http\Controllers\Users\UpdateUserPermissionsController;
use Illuminate\Support\Facades\Route;

Route::get('/', IndexController::class)->name('index');

Route::get('/contact', ContactUsPageController::class)->name('contact.create');
Route::post('/contact', ProcessContactUsController::class)->name('contact.store');

Route::middleware('guest')->group(function () {
    Route::get('/login', LoginController::class)->name('login.create');
    Route::post('/login', AuthenticateUserController::class)->name('login.store');
    Route::get('/register/{invite:token}', RegistrationController::class)->name('register.create');
    Route::post('/register', StoreRegistrationController::class)->name('register.store');
});

Route::middleware('auth')->group(function () {
    Route::post('logout', LogoutController::class)->name('auth.logout');

    Route::prefix('defibs')->name('defibs.')->group(function () {
        Route::get('/', ListDefibsController::class)->name('list')->can('defib.list');
        Route::post('/', StoreDefibController::class)->name('store')->can('defib.create');
        Route::get('/new', CreateDefibController::class)->name('create')->can('defib.create');
        Route::get('/{defib}', ViewDefibController::class)->name('view')->can('defib.view');
        Route::get('/{defib}/update', EditDefibController::class)->name('edit')->can('defib.update');
        Route::put('/{defib}', UpdateDefibController::class)->name('update')->can('defib.update');

        Route::prefix('/{defib}/inspections')->name('inspections.')->group(function () {
            Route::get('/new', CreateDefibInspectionController::class)->name('create')->can('defib.inspect');
            Route::post('/', StoreDefibInspectionController::class)->name('store')->can('defib.inspect');
        });

        Route::prefix('/{defib}/notes')->name('notes.')->group(function () {
            Route::get('/new', CreateDefibNoteController::class)->name('create')->can('defib.note');
            Route::post('/', StoreDefibNoteController::class)->name('store')->can('defib.note');
        });
    });

    Route::prefix('members')->name('members.')->group(function () {
        Route::get('/', ListMembersController::class)->name('list')->can('member.list');
        Route::post('/', StoreMemberController::class)->name('store')->can('member.create');
        Route::get('/new', CreateMemberController::class)->name('create')->can('member.create');
        Route::get('/{member}', ViewMemberController::class)->name('view')->can('member.view');
        Route::get('/{member}/update', EditMemberController::class)->name('edit')->can('member.update');
        Route::put('/{member}', UpdateMemberController::class)->name('update')->can('member.update');

        Route::prefix('/{member}/notes')->name('notes.')->group(function () {
            Route::get('/new', CreateMemberNoteController::class)->name('create')->can('member.note');
            Route::post('/', StoreMemberNoteController::class)->name('store')->can('member.note');
        });
    });

    Route::prefix('callouts')->name('callouts.')->group(function () {
        Route::get('/', ListCalloutsController::class)->name('list')->can('callout.list');
        Route::post('/', StoreCalloutController::class)->name('store')->can('callout.create');
        Route::get('/new', CreateCalloutController::class)->name('create')->can('callout.create');
        Route::get('/{callout}', ShowCalloutController::class)->name('show')->can('callout.view');
    });

    Route::prefix('users')->name('users.')->group(function () {
        Route::get('/', ListUsersController::class)->name('list')->can('user.list');
        Route::get('/invite', InviteUserController::class)->name('invite.create')->can('user.invite');
        Route::post('/invite', StoreUserInvitationController::class)->name('invite.store')->can('user.invite');
        Route::get('/{user}', ShowUserController::class)->name('show')->can('user.view');
        Route::get('/{user}/reports', ShowRequestedReportsController::class)->name('reports.show')->can('user.update');
        Route::put('/{user}/reports', StoreRequestedReportsController::class)->name('reports.store')->can('user.update');
        Route::get('/{user}/permissions', ShowUserPermissionsController::class)->name('permissions.show')->can('user.permissions');
        Route::put('/{user}/permissions', UpdateUserPermissionsController::class)->name('permissions.update')->can('user.permissions');
    });
});

app/Models/Member.php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Member extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'name',
        'phone',
        'email',
        'address_1',
        'address_2',
        'eircode',
        'title',
        'status',
        'cfr_certificate_number',
        'cfr_certificate_expiry',
        'volunteer_declaration',
        'garda_vetting_id',
        'garda_vetting_date',
        'cism_completed',
        'child_first_completed',
        'ppe_community_completed',
        'ppe_acute_completed',
        'hand_hygiene_completed',
        'hiqa_completed',
        'covid_return_completed',
        'ppe_assessment_completed',
    ];

    protected $casts = [
        'cfr_certificate_expiry' => 'date:Y-m-d',
        'volunteer_declaration' => 'date:Y-m-d',
        'garda_vetting_date' => 'date:Y-m-d',
        'cism_completed' => 'date:Y-m-d',
        'child_first_completed' => 'date:Y-m-d',
        'ppe_community_completed' => 'date:Y-m-d',
        'ppe_acute_completed' => 'date:Y-m-d',
        'hand_hygiene_completed' => 'date:Y-m-d',
        'hiqa_completed' => 'date:Y-m-d',
        'covid_return_completed' => 'date:Y-m-d',
        'ppe_assessment_completed' => 'date:Y-m-d',
    ];

    public function notes(): HasMany
    {
        return $this->hasMany(MemberNote::class);
    }
}

app/Http/Controllers/Members/CreateMemberController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Members;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class CreateMemberController extends Controller
{
    public function __invoke(Request $request): View
    {
        return view('members.create');
    }
}

app/Http/Controllers/Members/EditMemberController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Members;

use App\Http\Controllers\Controller;
use App\Models\Member;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class EditMemberController extends Controller
{
    public function __invoke(Request $request, Member $member): View
    {
        return view('members.update', ['member' => $member]);
    }
}

app/Http/Controllers/Members/ListMembersController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Members;

use App\Http\Controllers\Controller;
use App\Models\Member;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class ListMembersController extends Controller
{
    public function __invoke(Request $request): View
    {
        $members = Member::paginate(10);

        return view('members.list', ['members' => $members]);
    }
}

app/Http/Controllers/Members/Notes/CreateMemberNoteController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Members\Notes;

use App\Http\Controllers\Controller;
use App\Models\Member;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class CreateMemberNoteController extends Controller
{
    public function __invoke(Request $request, Member $member): View
    {
        return view('members.notes.create', ['member' => $member]);
    }
}

app/Http/Controllers/Members/Notes/StoreMemberNoteController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Members\Notes;

use App\Http\Controllers\Controller;
use App\Http\Requests\Members\Notes\StoreMemberNoteRequest;
use App\Models\Member;
use App\Models\MemberNote;
use Illuminate\Http\RedirectResponse;

class StoreMemberNoteController extends Controller
{
    public function __invoke(StoreMemberNoteRequest $request, Member $member): RedirectResponse
    {
        $note = new MemberNote($request->validated());
        $note->member_id = $member->id;
        $note->user_id = auth()->user()->id;
        $note->save();

        return redirect()->route('members.view', ['member' => $member])->with('success', 'Member note successfully added');
    }
}

app/Http/Controllers/Members/StoreMemberController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Members;

use App\Http\Controllers\Controller;
use App\Http\Requests\Members\StoreMemberRequest;
use App\Models\Member;
use Illuminate\Http\RedirectResponse;

class StoreMemberController extends Controller
{
    public function __invoke(StoreMemberRequest $request): RedirectResponse
    {
        $member = new Member($request->validated());
        $member->user_id = auth()->user()->id;
        $member->save();

        return redirect()->route('members.list')->with('success', 'New member successfully added');
    }
}

app/Http/Controllers/Members/UpdateMemberController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Members;

use App\Http\Controllers\Controller;
use App\Http\Requests\Members\UpdateMemberRequest;
use App\Models\Member;
use Illuminate\Http\RedirectResponse;

class UpdateMemberController extends Controller
{
    public function __invoke(UpdateMemberRequest $request, Member $member): RedirectResponse
    {
        $member->update($request->validated());

        return redirect()->route('members.view', ['member' => $member])->with('success', 'Member successfully updated');
    }
}

app/Http/Controllers/Members/ViewMemberController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Members;

use App\Http\Controllers\Controller;
use App\Models\Member;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class ViewMemberController extends Controller
{
    public function __invoke(Request $request, Member $member): View
    {
        $member->load(['notes.author']);

        return view('members.view', ['member' => $member]);
    }
}

app/View/Components/AppLayout.php
<?php

declare(strict_types=1);

namespace App\View\Components;

use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class AppLayout extends Component
{
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/members/create.blade.php
<x-app-layout>
    <div class="overflow-hidden bg-white shadow sm:rounded-lg">
        <div class="sm:flex sm:items-center py-5 px-4 sm:px-6 lg:px-8">
            <div class="sm:flex-auto">
                <h1 class="text-xl font-semibold text-gray-900">Add Member</h1>
            </div>
            <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
            </div>
        </div>
        <div class="border-t border-gray-200 px-4 py-5 sm:p-0">
            <form action="{{ route('members.store') }}" method="post">
                @csrf
                <dl class="sm:divide-y sm:divide-gray-200">
                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500"><label for="name">Name</label></dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <input type="text" name="name" id="name" class="block @error('name') border-red-500 @enderror w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm">
                            @error('name')
                                <div class="text-sm text-red-600">{{ $message }}</div>
                            @enderror
                        </dd>
                    </div>

                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500"><label for="role">Role</label></dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <input type="text" name="role" id="role" class="block @error('role') border-red-500 @enderror w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm">
                            @error('role')
                                <div class="text-sm text-red-600">{{ $message }}</div>
                            @enderror
                        </dd>
                    </div>

                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500"><label for="phone">Phone Number</label></dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <input type="text" name="phone" id="phone" class="block @error('phone') border-red-500 @enderror w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm">
                            @error('phone')
                                <div class="text-sm text-red-600">{{ $message }}</div>
                            @enderror
                        </dd>
                    </div>

                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500"><label for="email">Email Address</label></dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <input type="email" name="email" id="email" class="block @error('email') border-red-500 @enderror w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm">
                            @error('email')
                                <div class="text-sm text-red-600">{{ $message }}</div>
                            @enderror
                        </dd>
                    </div>

                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500"><label for="address_1">Address 1</label></dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <input type="text" name="address_1" id="address_1" class="block @error('address_1') border-red-500 @enderror w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm">
                            @error('address_1')
                                <div class="text-sm text-red-600">{{ $message }}</div>
                            @enderror
                        </dd>
                    </div>

                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500"><label for="address_2">Address 2</label></dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <input type="text" name="address_2" id="address_2" class="block @error('address_2') border-red-500 @enderror w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm">
                            @error('address_2')
                                <div class="text-sm text-red-600">{{ $message }}</div>
                            @enderror
                        </dd>
                    </div>

                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500"><label for="eircode">Eircode</label></dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <input type="text" name="eircode" id="eircode" class="block @error('eircode') border-red-500 @enderror w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm">
                            @error('eircode')
                                <div class="text-sm text-red-600">{{ $message }}</div>
                            @enderror
                        </dd>
                    </div>

                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500"><label for="status">Status</label></dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <select name="status" id="status" class="block @error('status') border-red-500 @enderror w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm">
                                <option value="inactive">Inactive</option>
                                <option value="active">Active</option>
                            </select>
                        </dd>
                    </div>

                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            <button type="submit" class="inline-flex justify-center rounded-md border border-transparent bg-red-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2">Add</button>
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <button type="button" class="rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2">Cancel</button>
                        </dd>
                    </div>
                </dl>
            </form>
        </div>
    </div>
</x-app-layout>

resources/views/members/list.blade.php
<x-app-layout>
    <div class="overflow-hidden bg-white shadow sm:rounded-lg px-4 sm:px-6 lg:px-8">
        <div class="sm:flex sm:items-center py-5">
            <div class="sm:flex-auto">
                <h1 class="text-xl font-semibold text-gray-900">Members</h1>
            </div>
            <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
                @can('member.create')
                    <a href="{{ route('members.create') }}">
                        <button type="button" class="inline-flex items-center justify-center rounded-md border border-transparent bg-red-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2 sm:w-auto">Add Member</button>
                    </a>
                @endcan
            </div>
        </div>
        <div class="flex flex-col">
            <div class="-my-2 -mx-4 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="inline-block min-w-full py-2 align-middle">
                    <div class="overflow-hidden shadow-sm ring-1 ring-black ring-opacity-5">
                        <table class="min-w-full divide-y divide-gray-300">
                            <thead class="bg-gray-50">
                            <tr>
                                <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6 lg:pl-8">Name</th>
                                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Phone Number</th>
                                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Email Address</th>
                                <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Status</th>
                                <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6 lg:pr-8">
                                    <span class="sr-only">View</span>
                                </th>
                            </tr>
                            </thead>
                            <tbody class="divide-y divide-gray-200 bg-white">
                                @foreach($members as $member)
                                    <tr>
                                        <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6">{{ $member->name }}</td>
                                        <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ $member->phone }}</td>
                                        <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ $member->email }}</td>
                                        <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">{{ ucfirst($member->status) }}</td>
                                        <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6">
                                            <a href="{{ route('members.view', ['member' => $member]) }}" class="text-red-600 hover:text-red-900">View<span class="sr-only">, {{ $member->name }}</span></a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            {{ $members->links('pagination::tailwind') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>