routes/web.php
<?php

declare(strict_types=1);

use App\Http\Controllers\Auth\AuthenticateUserController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\RegistrationController;
use App\Http\Controllers\Auth\StoreRegistrationController;
use App\Http\Controllers\Callouts\CreateCalloutController;
use App\Http\Controllers\Callouts\ListCalloutsController;
use App\Http\Controllers\Callouts\ShowCalloutController;
use App\Http\Controllers\Callouts\StoreCalloutController;
use App\Http\Controllers\Contact\ContactUsPageController;
use App\Http\Controllers\Contact\ProcessContactUsController;
use App\Http\Controllers\Defibs\CreateDefibController;
use App\Http\Controllers\Defibs\EditDefibController;
use App\Http\Controllers\Defibs\Inspections\CreateDefibInspectionController;
use App\Http\Controllers\Defibs\Inspections\StoreDefibInspectionController;
use App\Http\Controllers\Defibs\ListDefibsController;
use App\Http\Controllers\Defibs\Notes\CreateDefibNoteController;
use App\Http\Controllers\Defibs\Notes\StoreDefibNoteController;
use App\Http\Controllers\Defibs\StoreDefibController;
use App\Http\Controllers\Defibs\UpdateDefibController;
use App\Http\Controllers\Defibs\ViewDefibController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\Members\CreateMemberController;
use App\Http\Controllers\Members\EditMemberController;
use App\Http\Controllers\Members\ListMembersController;
use App\Http\Controllers\Members\Notes\CreateMemberNoteController;
use App\Http\Controllers\Members\Notes\StoreMemberNoteController;
use App\Http\Controllers\Members\StoreMemberController;
use App\Http\Controllers\Members\UpdateMemberController;
use App\Http\Controllers\Members\ViewMemberController;
use App\Http\Controllers\Users\InviteUserController;
use App\Http\Controllers\Users\ListUsersController;
use App\Http\Controllers\Users\ShowRequestedReportsController;
use App\Http\Controllers\Users\ShowUserController;
use App\Http\Controllers\Users\ShowUserPermissionsController;
use App\Http\Controllers\Users\StoreRequestedReportsController;
use App\Http\Controllers\Users\StoreUserInvitationController;
use App\Http\Controllers\Users\UpdateUserPermissionsController;
use Illuminate\Support\Facades\Route;

Route::get('/', IndexController::class)->name('index');

Route::get('/contact', ContactUsPageController::class)->name('contact.create');
Route::post('/contact', ProcessContactUsController::class)->name('contact.store');

Route::middleware('guest')->group(function () {
    Route::get('/login', LoginController::class)->name('login.create');
    Route::post('/login', AuthenticateUserController::class)->name('login.store');
    Route::get('/register/{invite:token}', RegistrationController::class)->name('register.create');
    Route::post('/register', StoreRegistrationController::class)->name('register.store');
});

Route::middleware('auth')->group(function () {
    Route::post('logout', LogoutController::class)->name('auth.logout');

    Route::prefix('defibs')->name('defibs.')->group(function () {
        Route::get('/', ListDefibsController::class)->name('list')->can('defib.list');
        Route::post('/', StoreDefibController::class)->name('store')->can('defib.create');
        Route::get('/new', CreateDefibController::class)->name('create')->can('defib.create');
        Route::get('/{defib}', ViewDefibController::class)->name('view')->can('defib.view');
        Route::get('/{defib}/update', EditDefibController::class)->name('edit')->can('defib.update');
        Route::put('/{defib}', UpdateDefibController::class)->name('update')->can('defib.update');

        Route::prefix('/{defib}/inspections')->name('inspections.')->group(function () {
            Route::get('/new', CreateDefibInspectionController::class)->name('create')->can('defib.inspect');
            Route::post('/', StoreDefibInspectionController::class)->name('store')->can('defib.inspect');
        });

        Route::prefix('/{defib}/notes')->name('notes.')->group(function () {
            Route::get('/new', CreateDefibNoteController::class)->name('create')->can('defib.note');
            Route::post('/', StoreDefibNoteController::class)->name('store')->can('defib.note');
        });
    });

    Route::prefix('members')->name('members.')->group(function () {
        Route::get('/', ListMembersController::class)->name('list')->can('member.list');
        Route::post('/', StoreMemberController::class)->name('store')->can('member.create');
        Route::get('/new', CreateMemberController::class)->name('create')->can('member.create');
        Route::get('/{member}', ViewMemberController::class)->name('view')->can('member.view');
        Route::get('/{member}/update', EditMemberController::class)->name('edit')->can('member.update');
        Route::put('/{member}', UpdateMemberController::class)->name('update')->can('member.update');

        Route::prefix('/{member}/notes')->name('notes.')->group(function () {
            Route::get('/new', CreateMemberNoteController::class)->name('create')->can('member.note');
            Route::post('/', StoreMemberNoteController::class)->name('store')->can('member.note');
        });
    });

    Route::prefix('callouts')->name('callouts.')->group(function () {
        Route::get('/', ListCalloutsController::class)->name('list')->can('callout.list');
        Route::post('/', StoreCalloutController::class)->name('store')->can('callout.create');
        Route::get('/new', CreateCalloutController::class)->name('create')->can('callout.create');
        Route::get('/{callout}', ShowCalloutController::class)->name('show')->can('callout.view');
    });

    Route::prefix('users')->name('users.')->group(function () {
        Route::get('/', ListUsersController::class)->name('list')->can('user.list');
        Route::get('/invite', InviteUserController::class)->name('invite.create')->can('user.invite');
        Route::post('/invite', StoreUserInvitationController::class)->name('invite.store')->can('user.invite');
        Route::get('/{user}', ShowUserController::class)->name('show')->can('user.view');
        Route::get('/{user}/reports', ShowRequestedReportsController::class)->name('reports.show')->can('user.update');
        Route::put('/{user}/reports', StoreRequestedReportsController::class)->name('reports.store')->can('user.update');
        Route::get('/{user}/permissions', ShowUserPermissionsController::class)->name('permissions.show')->can('user.permissions');
        Route::put('/{user}/permissions', UpdateUserPermissionsController::class)->name('permissions.update')->can('user.permissions');
    });
});

app/Models/Defib.php
<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Defib extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'name',
        'location',
        'coordinates',
        'display_on_map',
        'model',
        'serial',
        'owner',
        'last_inspected_at',
        'last_inspected_by',
        'last_serviced_at',
        'pads_expire_at',
        'battery_expires_at',
    ];

    protected $casts = [
        'last_inspected_at' => 'datetime:Y-m-d',
        'pads_expire_at' => 'datetime:Y-m-d',
        'last_serviced_at' => 'datetime:Y-m-d',
        'display_on_map' => 'boolean',
        'serial' => 'string',
        'battery_expires_at' => 'datetime:Y-m-d',
    ];

    public function inspections(): HasMany
    {
        return $this->hasMany(DefibInspection::class);
    }

    public function notes(): HasMany
    {
        return $this->hasMany(DefibNote::class);
    }

    public function scopePublic(Builder $query): Builder
    {
        return $query->where('display_on_map', true);
    }
}

app/Http/Controllers/Defibs/CreateDefibController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Defibs;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class CreateDefibController extends Controller
{
    public function __invoke(Request $request): View
    {
        return view('defibs.create');
    }
}

app/Http/Controllers/Defibs/EditDefibController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Defibs;

use App\Http\Controllers\Controller;
use App\Models\Defib;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class EditDefibController extends Controller
{
    public function __invoke(Request $request, Defib $defib): View
    {
        return view('defibs.update', ['defib' => $defib]);
    }
}

app/Http/Controllers/Defibs/Inspections/CreateDefibInspectionController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Defibs\Inspections;

use App\Http\Controllers\Controller;
use App\Models\Defib;
use App\Models\Member;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class CreateDefibInspectionController extends Controller
{
    public function __invoke(Request $request, Defib $defib): View
    {
        $members = Member::all();

        return view('defibs.inspections.create', ['defib' => $defib, 'members' => $members]);
    }
}

app/Http/Controllers/Defibs/Inspections/StoreDefibInspectionController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Defibs\Inspections;

use App\Events\DefibInspected;
use App\Http\Controllers\Controller;
use App\Http\Requests\Defibs\Inspections\StoreDefibInspectionRequest;
use App\Models\Defib;
use App\Models\DefibInspection;
use App\Models\Member;
use Illuminate\Http\RedirectResponse;

class StoreDefibInspectionController extends Controller
{
    public function __invoke(StoreDefibInspectionRequest $request, Defib $defib): RedirectResponse
    {
        $member = Member::query()->where('id', '=', $request->get('member_id'))->first();

        $inspection = new DefibInspection($request->validated());
        $inspection->user_id = auth()->user()->id;
        $inspection->defib_id = $defib->id;
        $inspection->save();

        $defib->pads_expire_at = $request->get('pads_expire_at');
        $defib->battery_expires_at = $request->get('battery_expires_at');
        $defib->last_inspected_at = $request->get('inspected_at');
        $defib->last_inspected_by = $member->name;
        $defib->save();

        DefibInspected::dispatch($defib, $inspection);

        return redirect()->route('defibs.view', ['defib' => $defib->id])->with('success', 'Defib inspection successfully added');
    }
}

app/Http/Controllers/Defibs/ListDefibsController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Defibs;

use App\Http\Controllers\Controller;
use App\Models\Defib;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class ListDefibsController extends Controller
{
    public function __invoke(Request $request): View
    {
        $defibs = Defib::paginate(10);

        return view('defibs.list', ['defibs' => $defibs]);
    }
}

app/Http/Controllers/Defibs/Notes/CreateDefibNoteController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Defibs\Notes;

use App\Http\Controllers\Controller;
use App\Models\Defib;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class CreateDefibNoteController extends Controller
{
    public function __invoke(Request $request, int $id): View
    {
        $defib = Defib::find($id);

        return view('defibs.notes.create', ['defib' => $defib]);
    }
}

app/Http/Controllers/Defibs/Notes/StoreDefibNoteController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Defibs\Notes;

use App\Http\Controllers\Controller;
use App\Http\Requests\Defibs\Notes\StoreDefibNoteRequest;
use App\Models\Defib;
use App\Models\DefibNote;
use Illuminate\Http\RedirectResponse;

class StoreDefibNoteController extends Controller
{
    public function __invoke(StoreDefibNoteRequest $request, Defib $defib): RedirectResponse
    {
        $note = new DefibNote($request->validated());
        $note->defib_id = $defib->id;
        $note->user_id = auth()->user()->id;
        $note->save();

        return redirect()->route('defibs.view', ['defib' => $defib->id])->with('success', 'Defib note successfully added');
    }
}

app/Http/Controllers/Defibs/StoreDefibController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Defibs;

use App\Http\Controllers\Controller;
use App\Http\Requests\Defibs\UpsertDefibRequest;
use App\Models\Defib;
use Illuminate\Http\RedirectResponse;

class StoreDefibController extends Controller
{
    public function __invoke(UpsertDefibRequest $request): RedirectResponse
    {
        $defib = new Defib($request->validated());
        $defib->user_id = auth()->user()->id;
        $defib->save();

        return redirect()->route('defibs.list')->with('success', 'Defib successfully added');
    }
}

app/Http/Controllers/Defibs/UpdateDefibController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Defibs;

use App\Http\Controllers\Controller;
use App\Http\Requests\Defibs\UpsertDefibRequest;
use App\Models\Defib;
use Illuminate\Http\RedirectResponse;

class UpdateDefibController extends Controller
{
    public function __invoke(UpsertDefibRequest $request, Defib $defib): RedirectResponse
    {
        $defib->update($request->validated());

        return redirect()->route('defibs.view', ['defib' => $defib->id])->with('success', 'Defib successfully updated');
    }
}

app/Http/Controllers/Defibs/ViewDefibController.php
<?php

declare(strict_types=1);

namespace App\Http\Controllers\Defibs;

use App\Http\Controllers\Controller;
use App\Models\Defib;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class ViewDefibController extends Controller
{
    public function __invoke(Request $request, Defib $defib): View
    {
        $defib->load(['notes.author', 'inspections.member']);

        return view('defibs.view', ['defib' => $defib]);
    }
}

app/View/Components/AppLayout.php
<?php

declare(strict_types=1);

namespace App\View\Components;

use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class AppLayout extends Component
{
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/defibs/inspections/create.blade.php
<x-app-layout>
    <div class="overflow-hidden bg-white shadow sm:rounded-lg">
        <div class="sm:flex sm:items-center py-5 px-4 sm:px-6 lg:px-8">
            <div class="sm:flex-auto">
                <h1 class="text-xl font-semibold text-gray-900">Add Defib Inspection</h1>
            </div>
            <div class="mt-4 sm:mt-0 sm:ml-16 sm:flex-none">
            </div>
        </div>
        <div class="border-t border-gray-200 px-4 py-5 sm:p-0">
            <form action="{{ route('defibs.inspections.store', ['defib' => $defib->id]) }}" method="post">
                @csrf
                <dl class="sm:divide-y sm:divide-gray-200">
                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500"><label for="member_id">Inspected By</label></dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <select type="text" name="member_id" id="member_id" class="block @error('member_id') border-red-500 @enderror w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm">
                                @foreach($members as $member)
                                    <option value="{{ $member->id }}">{{ $member->name }}</option>
                                @endforeach
                            </select>
                            @error('member_id')
                                <div class="text-sm text-red-600">{{ $message }}</div>
                            @enderror
                        </dd>
                    </div>

                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500"><label for="inspected_at">Inspected On</label></dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <input type="date" name="inspected_at" id="inspected_at" class="block @error('inspected_at') border-red-500 @enderror w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm">
                            @error('inspected_at')
                                <div class="text-sm text-red-600">{{ $message }}</div>
                            @enderror
                        </dd>
                    </div>

                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500"><label for="pads_expire_at">Pads Expire On</label></dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <input type="date" name="pads_expire_at" id="pads_expire_at" class="block @error('pads_expire_at') border-red-500 @enderror w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm">
                            @error('pads_expire_at')
                                <div class="text-sm text-red-600">{{ $message }}</div>
                            @enderror
                        </dd>
                    </div>

                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500"><label for="battery_expires_at">Battery Expires On</label></dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <input type="date" name="battery_expires_at" id="battery_expires_at" class="block @error('battery_expires_at') border-red-500 @enderror w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm">
                            @error('battery_expires_at')
                                <div class="text-sm text-red-600">{{ $message }}</div>
                            @enderror
                        </dd>
                    </div>

                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500"><label for="notes">Notes</label></dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <textarea rows="5" name="notes" id="notes" class="block @error('notes') border-red-500 @enderror w-full max-w-lg rounded-md border-gray-300 shadow-sm focus:border-red-500 focus:ring-red-500 sm:text-sm"></textarea>
                            @error('notes')
                                <div class="text-sm text-red-600">{{ $message }}</div>
                            @enderror
                        </dd>
                    </div>

                    <div class="py-4 sm:grid sm:grid-cols-3 sm:gap-4 sm:py-5 sm:px-6">
                        <dt class="text-sm font-medium text-gray-500">
                            <button type="submit" class="inline-flex justify-center rounded-md border border-transparent bg-red-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2">Add Inspection</button>
                        </dt>
                        <dd class="mt-1 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <a href="{{ route('defibs.view', ['defib' => $defib->id]) }}">
                                <button type="button" class="rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2">Cancel</button>
                            </a>
                        </dd>
                    </div>
                </dl>
            </form>
        </div>
    </div>
</x-app-layout>